# Generated by Django 6.1.1 on 2026-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_task_category_remove_note_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
